services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    user: root:root
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.config.file=/etc/prometheus/web.yml
      - --storage.tsdb.path=/prometheus
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
    healthcheck:
      test: [ "CMD", "wget", "--no-check-certificate", "--quiet", "--tries=1", "--spider", "https://localhost:9090/-/healthy" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./web.yml:/etc/prometheus/web.yml
      - "${TLS_CERT_PATH}:/etc/ssl/cert.pem:ro"
      - "${TLS_KEY_PATH}:/etc/ssl/key.pem:ro"
      - /var/run/docker.sock:/var/run/docker.sock:ro # Used for Docker service discovery