basic_auth_users:
  truenas_admin: "$2a$10$hyyEbuZCnjdo15lqqXpEGuMMTEseWT7F9Ricm1TLq5SkKASMSjp.m"
  grafana: "$2a$10$xwd4YLAgS9aUGpLIygmlduPDlbKa0BKMNyhPZiDihE7tIPIb.zE4O"

tls_server_config:
  cert_file: /run/secrets/ssl_cert
  key_file: /run/secrets/ssl_key