name: opencloud

include:
  - clamav/compose.yml
  - collabora/compose.yml
  - radicale/compose.yml
  - tika/compose.yml
  - web-extensions/compose.yml
  - opencloud/compose.yml

networks:
  default:
    name: servarr
  proxy:
    name: proxy
    external: true

services: {}