name: auth

secrets:
  smtp_password:
    environment: "SMTP_PASSWORD"

include:
  - lldap/compose.yml
  - authelia/compose.yml

networks:
  default:
    name: auth
  proxy:
    name: proxy
    external: true

services: {}