services:
  gitea:
    container_name: gitea
    image: docker.io/gitea/gitea:latest
    depends_on:
      - gitea-postgres
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 500M
    networks:
      - default
      - proxy
    ports:
      - "2222:2222"
    volumes:
      - "${DATA_PATH}:/data"
    labels:
      traefik.enable: true
      traefik.http.routers.gitea.rule: "Host(`${DOMAIN}`)"
      traefik.http.routers.gitea.entrypoints: websecure
      traefik.http.services.gitea.loadbalancer.server.port: 3000
    env_file:
      - gitea.env

  gitea-postgres:
    container_name: gitea-postgres
    image: postgres:18-alpine
    restart: unless-stopped
    shm_size: 128mb
    deploy:
      resources:
        limits:
          memory: 200M
    volumes:
      - "${DB_PATH}:/var/lib/postgresql/18/docker"
    env_file:
      - postgres.env