name: servarr

include:
  - includes/qbittorrent.yml
  - includes/qui.yml
  - includes/jellyfin.yml
  - includes/jellyseerr.yml
  - includes/jellystat.yml
  - includes/bazarr.yml
  - includes/prowlarr.yml
  - includes/radarr.yml
  - includes/sonarr.yml
  - includes/lidarr.yml
  - includes/unpackerr.yml
  - includes/recyclarr.yml
  - includes/cleanuparr.yml
  - includes/autobrr.yml
  - includes/fileflows.yml

services: {}