name: metrics

include:
  - node-exporter/compose.yml
#  - gpu-exporter/compose.yml
  - prometheus/compose.yml
  - grafana/compose.yml

networks:
  default:
    name: metrics
    external: true
  proxy:
    name: proxy
    external: true

services: {}